### PR TITLE
Set swagger-parser version to 2.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by jmini**

### CODE REVIEW

**Comment by jmini** [comment]
The next swagger-parser version will be published soon. See https://github.com/swagger-api/swagger-parser/issues/717

I would like to update the `swagger-snapshot` branch to make some tests.

**Comment by jmini** [comment]
@quen2404: can you also merge `master` into `swagger-snapshot` with a merge commit, in order to pick up all the changes made on master since april?

**Comment by quen2404** [comment]
@jmini i haven't access to my IDE currently, so if you want a fast merge, please make a PR. Else I will do it tomorrow.

**Comment by jmini** [comment]
discussed merge `master` into `swagger-snapshot` => #46

**Pull request merged**
