### PR TITLE
Report causes for compatibility breakage

### PR DESCRIPTION
**Pull request by thiagoarrais**
First of all, this is a work in progress. I'm trying to add details about broken compatibility and tried to start with properties removed from responses. Just let me know if I'm going in the right direction.

I'm currently getting the output below with this code ([old][gist_old] and [new][gist_new] specs available as a gist):

```
==========================================================================
==                            API CHANGE LOG                            ==
==========================================================================
                                  My API                                  
--------------------------------------------------------------------------
--                            What's Changed                            --
--------------------------------------------------------------------------
- GET    /api/v1/addons
  Return Type:
    - Changed 422 Unprocessable Entity
      Media types:
        - Changed application/json
          Schema: Broken compatibility
          Missing property: .originConstraint.leafBean
--------------------------------------------------------------------------
--                                Result                                --
--------------------------------------------------------------------------
                 API changes broke backward compatibility                 
--------------------------------------------------------------------------
```

I have added the `Missing property` line. The property path is a little rough right now, but I plan on working on this later. For this test case, my ideal output should be something along these lines:

```
Missing property: [Message.originConstraint.leafBean]
```

Do you see this getting merged if it we're able to (1) get to an acceptable path format and (2) include the detailed reported in the HTML and markdown outputs?

Related to #18

[gist_old]: https://gist.githubusercontent.com/thiagoarrais/1ceb28882eba3bd333e775de0ce69648/raw/7f734ff92b2265e8f08da55f3508c9135fdb0915/openapi-old.json
[gist_new]: https://gist.githubusercontent.com/thiagoarrais/1ceb28882eba3bd333e775de0ce69648/raw/7f734ff92b2265e8f08da55f3508c9135fdb0915/openapi-new.json

### CODE REVIEW

**Comment by thiagoarrais** [comment]
@quen2404: couldn't pin point where Renderer tests should go. Should I write some? Where?

**Comment by thiagoarrais** [comment]
HTML reporting is done and Markdown was covered already (which was a pleasant surprise). I'm considering this funcionally done. But I'll still try some refactoring by spliting the incompatibility listing and printing responsability. I believe the listing should go inside the `ChangedXXXX` classes and `XxxxRender` should only print it. Do you see any problems with that?

**Comment by michalchmura** [comment]
Any updates on this?

**Comment by thiagoarrais** [comment]
I'm still willing to work on it. It needs some refactoring in my opinion. But I would like to confirm interest in this funcionality-wise before going on. Does the current proposed output seem good to you, @michalchmura?

**Comment by michalchmura** [comment]
@thiagoarrais yes, the proposed output seems great! It'd be good to be able to list addition/deletion but also altering the property names.

I've built the project from your branch and I couldn't quite get it to output it.

**Comment by thiagoarrais** [comment]
This is what I'm getting. You can try it using these input files: [remove_inner_prop_1.yaml](https://gist.githubusercontent.com/thiagoarrais/e91909b7b00b995b419d7d86cacb426e/raw/09c5b65f4d3a053e2906551308633bf9e4869497/remove_inner_prop_1.yaml) and [remove_inner_prop_2.yaml](https://gist.githubusercontent.com/thiagoarrais/e91909b7b00b995b419d7d86cacb426e/raw/09c5b65f4d3a053e2906551308633bf9e4869497/remove_inner_prop_2.yaml):

```
$ java -jar target/openapi-diff-2.0.0-SNAPSHOT-jar-with-dependencies.jar src/test/resources/remove_inner_prop_1.yaml src/test/resources/remove_inner_prop_2.yaml
==========================================================================
==                            API CHANGE LOG                            ==
==========================================================================
                             Swagger Petstore                             
--------------------------------------------------------------------------
--                            What's Changed                            --
--------------------------------------------------------------------------
- GET    /pet/findByStatus
  Return Type:
    - Changed 200 OK
      Media types:
        - Changed application/json
          Schema: Broken compatibility
          Missing property: pets[n].bark
          Changed property type: pets[n].aaaa
          Changed property type: pets[n].tttt
          Missing property: pets[n].puppies[n].name
          Missing property: pets[n].puppies[n].nick
--------------------------------------------------------------------------
--                                Result                                --
--------------------------------------------------------------------------
                 API changes broke backward compatibility                 
--------------------------------------------------------------------------
```

**Comment by thiagoarrais** [comment]
I'm currently focusing on getting removed properties working. Can you get me some before/after inputs and what you'd like too see outputed for your use case? I may be able to fit it into this PR.

**Comment by thiagoarrais** [comment]
I'm happy with the state of the code as of 856b426. This is ready for review and subsequent merging. It admittedly doesn't cover all cases for compatibility breakage (adding required parameter, for example), but it already covers the uses cases I need for now and adds an extensible structure so that it can be improved in future PRs.

**Comment by quen2404** [comment]
Hi @thiagoarrais, 
thank you for your work. I'm currently looking what you've done :)

**Pull request merged**
